# Generated by Django 3.0.2 on 2020-01-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_calorierecord_on_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calorierecord',
            options={'ordering': ['date'], 'verbose_name': 'calorie record', 'verbose_name_plural': 'calorie records'},
        ),
        migrations.RenameField(
            model_name='calorierecord',
            old_name='on_target',
            new_name='on_goal',
        ),
    ]
